trigger:
- task: BlackDuckSecurityScan@2
  inputs:
    scanType: 'polaris'
    polarisServerUrl: 'test'
    polarisAccessToken: 'test'
    polarisAssessmentTypes: 'test'


- main

pool:
  name: Default   # <-- use your self-hosted pool name, "Default" by default
 
steps:
- script: echo Hello from self-hosted Windows agent!
  displayName: 'Run a one-line script'

- powershell: |
    Write-Host "Running on Windows self-hosted agent"
    Write-Host "Machine name: $env:COMPUTERNAME"
    Write-Host "User: $env:USERNAME"
  displayName: 'Run PowerShell on Windows'

- task: FortifyScanCentralSAST@7
  inputs:
    scanCentralCtrlUrl: 'http://OTX-4RJ8874:9991/scancentral-ctrl/'
    # scanCentralCtrlUrl: '$(ScanCentralCtrlUrl)'
   # scanCentralClientToken: '$(ScanCentral.ClientToken)'
    scanCentralClientToken: fortify
    sscUrl: 'http://otx-4rj8874:9999/ssc'
    # sscUrl: '$(ScanCentral.SscUrl)'
    sscCiToken: c0b823fd-1961-461f-b518-9889f608dd01
    uploadToSSC: true
    applicationIdentifierType: 'byId'
    applicationVersionId: '5'
    buildTool: 'none'
